//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Esoft_ProjectEntities5 : DbContext
    {
        public Esoft_ProjectEntities5()
            : base("name=Esoft_ProjectEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SupplySet> SupplySet { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Недвижимость> Недвижимость { get; set; }
        public virtual DbSet<Риелтор> Риелтор { get; set; }
    }
}
